services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    CmsIg\Seal\Adapter\AdapterFactoryInterface:
      tags: [ 'seal.adapter_factory' ]

  Lochmueller\Seal\:
    resource: '../Classes/*'

  # ViewHelpers with constructor injection have to be public, so that the
  # ViewHelperResolver is able to fetch them from the container.
  Lochmueller\Seal\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true