services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    CmsIg\Seal\Adapter\AdapterFactoryInterface:
      tags: [ 'seal.adapter_factory' ]

  Lochmueller\Seal\:
    resource: '../Classes/*'